default_platform(:android)

platform :android do
  desc "Upload signed AAB/APK to Play closed track"
  lane :deploy_closed do
    json_key = '/tmp/google-play.json'
    aab = Dir["./artifacts/*.aab"].first
    apk = Dir["./artifacts/*.apk"].first

    if aab
      upload_to_play_store(track: 'closed', aab: aab, json_key: json_key)
    elsif apk
      upload_to_play_store(track: 'closed', apk: apk, json_key: json_key)
    else
      UI.user_error!("No AAB or APK found in ./artifacts to upload to Play Store")
    end
  end
end
